### ISSUE TITLE
Asymmetric enemies face the wrong direction

### ISSUE THREAD

**Issue by R3Ked** [v6cord/VVVVVV-CE#7]
* [x] Fish (Edge Games)
* [x] ZZT Centipedes (Sweeney's Maze)
* [x] Mannequins (Short Circuit)
  * These don't have a sprite facing left.

**Comment by InfoTeddy** [comment]
We can't do much about the runners, there isn't a sprite in the game that has them point left.

Either way, given how the game works, I'm not sure fixing ZZT centipedes and the Edge Games fish is easy without doing some hacky things.

**Comment by R3Ked** [comment]
I'm not sure about this either, but couldn't you just turn the sprite when the enemy points a direction?

**Comment by InfoTeddy** [comment]
We'd have to change some of the rendering code for that, plus add a flag to each enemy to signal that the enemy's sprite should be turned when touching a wall. Doesn't sound hard, but this isn't a high priority right now.

**Comment by InfoTeddy** [comment]
Also, it looks like their facing direction depends on their x-value, which can seem random unless you carefully pay attention to where you place those enemies.

**Comment by R3Ked** [comment]
Forgive me if I'm not understanding something here, but nothing got fixed. They still don't turn the right way.

**Comment by InfoTeddy** [comment]
They're fixed in the latest pre-release, which has not been released yet.

You can download a CI build by going to [the commit log](/v6cord/VVVVVV-CE/commits/master), clicking the latest green checkmark, clicking any link in the pop-up that pops up (it doesn't matter), then in the upper-right corner clicking on Artifacts, then select the build for your operating system.

Alternatively, you can wait until pre-release 2 comes out.

**Comment by InfoTeddy** [comment]
Here's the link to the latest CI build (I presume you're still on Windows): https://github.com/v6cord/VVVVVV-CE/suites/577875888/artifacts/3969451
